# Generated by Django 3.2 on 2021-04-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210420_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='total',
            field=models.DecimalField(db_column='nb_total', decimal_places=2, default=0.0, max_digits=16),
        ),
    ]
